title: Yangyu Li / Applied Geoinformatics
email: yangyu.li@stud.plus.ac.at
timezone: Europe/Vienna
description: >- # this means to ignore newlines until "baseurl:"
  © 2026 by Yangyu Li.
  Powered by <a href="https://jekyllrb.com">Jekyll</a> & <a href="https://github.com">GitHub</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: yangyu_li_
github_username: YangyuLi-GIS

# Build settings
theme: minima
plugins:
  - jekyll-feed

# header arange
header_pages:
  - index.markdown
  - ePortfolio.markdown
  - CV.markdown
  - Blog.markdown
  - Contact.markdown

# ePortfolio page
collections:
  lectures:
    output: true
